### ISSUE TITLE
hotfix suggestion - wp-openapi/src/Spec/Path.php

### ISSUE THREAD

**Issue by davask** [moon0326/wp-openapi#37]
Installing the plugin I got the following error following that url `https://my.web.site/wp-json-openapi/?namespace=all`

```
[06-Jan-2024 08:39:11 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: 
                options is not allowed. It must be one of get,post,patch,delete,put in /path/to/wp/wp-content/plugins/wp-openapi/src/Spec/Operation.php:51
Stack trace:
#0 /path/to/wp/wp-content/plugins/wp-openapi/src/Spec/Path.php(74): WPOpenAPI\Spec\Operation->__construct()
#1 /path/to/wp/wp-content/plugins/wp-openapi/src/SchemaGenerator.php(80): WPOpenAPI\Spec\Path->generateOperationsFromRouteArgs()
#2 /path/to/wp/wp-content/plugins/wp-openapi/wp-openapi.php(142): WPOpenAPI\SchemaGenerator->generate()
#3 /path/to/wp/wp-content/plugins/wp-openapi/wp-openapi.php(223): WPOpenAPI->sendOpenAPISchema()
#4 /path/to/wp/wp-includes/class-wp-hook.php(324): {closure}()
#5 /path/to/wp/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /path/to/wp/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /path/to/wp/wp-includes/class-wp.php(830): do_action_ref_array()
#8 /path/to/wp/wp-includes/functions.php(1336): WP->main()
#9 /path/to/wp/wp-blog-header.php(16): wp()
#10 /path/to/wp/index.php(17): require('...')
#11 {main}
  thrown in /path/to/wp/wp-content/plugins/wp-openapi/src/Spec/Operation.php on line 51
```

here is my suggested hotfix

```
diff --git a/wp-content/plugins/wp-openapi/src/Spec/Path.php b/wp-content/plugins/wp-openapi/src/Spec/Path.php
index 7cc782704f..ecf7c60bfe 100644
--- a/wp-content/plugins/wp-openapi/src/Spec/Path.php
+++ b/wp-content/plugins/wp-openapi/src/Spec/Path.php
@@ -71,6 +71,7 @@ class Path {
                        foreach ( $arg['methods'] as $method => $value ) {
                                $description = $arg['description'] ?? '';
                                $method      = strtolower( $method );
+        if($method == 'options') continue;
                                $op          = new Operation( $method, $responses );
                                $op->setDescription( $description );
                                $op->generateParametersFromRouteArgs( $method, $arg['args'], $this->pathVariables, $th
is->path );
```

**Comment by moon0326** [comment]
Sorry for the delay in response. I should update my github notification preference 🤦 

It looks like I missed options. I'll update it soon.
